spring:
  servlet:
    encoding:
      charset: UTF-8
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: challenge05
  datasource:
    url: jdbc:postgresql://url
    username: usrname
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        default_schema: schemaName
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

security:
  jwt:
    secret-key: 4G7oeI/qXfMR5yM27r4lF6xFbN7YoGxH2OV9jhb4k2GZLoUz9ftq6lKwtt8t3S5BtBwy8v5leFjl/dwU74LuYg==
    expiration-time: 3600000
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer: DEBUG
